jobs:
  apply-templates:
    name: Check For Uncomitted Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Discard all uncommitted changes
        run: |
          git reset --hard HEAD
          git clean -fdx
      - name: Apply Templates
        run: ./apply-templates.sh
      - name: Check Git Status
        run: |
          status="$(git status --short)"
          if [ -n "$status" ]; then
            echo "Uncommitted changes detected:"
            echo "$status"
            exit 1
          fi
